### ISSUE TITLE
Please tag releases on dockerhub

### ISSUE THREAD

**Issue by raphink** [cburki/docker-nginx-rproxy-auth#1]
The last version of the container image broke because it switched the listening port from 80 to $SERVICE_PORT (which was 8080 in our case).

Tagging releases on dockerhub would avoid random upgrades with breaking changes, so it would be very much appreciated!

**Comment by cburki** [comment]
I have just added the 1.0.1 tag which is also available on the docker hub.

Sorry for the inconvenience.

**Comment by raphink** [comment]
No problem, thank you.
